producers-service:
  property: producers-service PROD

server:
  port: 0

spring:
  application:
    name: producers-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST_PRODUCERS:localhost}:${POSTGRES_PORT_PRODUCERS:5433}/${POSTGRES_DB_PRODUCERS:producers_db}
    username: ${POSTGRES_USER_PRODUCERS:producers_user}
    password: ${POSTGRES_PASSWORD_PRODUCERS:producers_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URLL:http://localhost:8761/eureka/}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
    reactor.netty.http.server: INFO
    org.springframework.cloud.netflix: INFO
    com.netflix.eureka: INFO
    org.springframework.web.reactive: INFO
    org.springframework.web: INFO
    org.springframework.boot.autoconfigure: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: OFF
    org.springframework.data.jpa: INFO
    com.agroflow: INFO
